substitutions:
  _IMAGE: helloworld
  _REGION: europe-west1

images:
- gcr.io/${PROJECT_ID}/${_IMAGE}


steps:
- id: docker-pull-cache
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/${PROJECT_ID}/${_IMAGE}:latest || exit 0']

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE}', '.']

- id: docker-push
  name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE}']

- id: create-attestation
  name: gcr.io/${PROJECT_ID}/cloud-sdk-beta
  entrypoint: gcloud
  args:
    - -c 
    - --project ${PROJECT_ID} beta container binauthz attestations sign-and-create --artifact-url=$(gcloud container images describe gcr.io/${PROJECT_ID}/${_IMAGE} '--format=value(image_summary.fully_qualified_digest)') --keyversion=projects/${PROJECT_ID}/locations/${_REGION}/keyRings/binauth/cryptoKeys/binauth/cryptoKeyVersions/1 --attestor projects/${PROJECT_ID}/attestors/me

- id: deploy-cloud-run
  name: gcr.io/${PROJECT_ID}/cloud-sdk-beta
  entrypoint: gcloud
  args:
    - --project
    - ${PROJECT_ID}
    - run
    - deploy
    - ${_IMAGE}
    - --image
    - gcr.io/${PROJECT_ID}/${_IMAGE}
    - --region
    - ${_REGION}
    - --platform
    - managed
